Building Docs
dl9pf/agl-docs pull request #1
Opened 2020-09-28 11:43 UTC by growupboron

Updated with the build docs.

2020-09-28 11:44 UTC, dl9pf approved these changes

2020-09-28 11:45 UTC, dl9pf requested changes
See: Renesas RCar Salvator/H3

Renesas RCar M3 w Salvator Board   ->  Renesas RCar Salvator/M3

2020-09-29 14:35 UTC, dl9pf approved these changes

2020-09-29 14:36 UTC, dl9pf approved these changes

2020-09-29 14:36 UTC, dl9pf commented
Ok, what about the Yocto Doc link versioning ?

2020-09-29 14:36 UTC, merged

2020-09-30 03:40 UTC, growupboron commented
I think, I updated most of the doc to 3.1.2, I will look into if we can set a global variable in the config file, and update that instead of manually doing it by hand.